version: '3.7'

services:
  app-php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: unicorn-php
    environment:
      - PHP_IDE_CONFIG=serverName=someproject-server
    depends_on:
      - db-postgresql
    volumes:
      - ./../backend_src:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: unicorn-nginx
    depends_on:
      - app-php
    ports:
      - 80:80
    volumes:
      - ./../backend_src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db-postgresql:
    build:
      context: ./postgersql
      dockerfile: Dockerfile
    image: unicorn-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_SU}
      POSTGRES_PASSWORD: ${POSTGRES_SU_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgersql/data:/var/lib/postgresql/data
      - ./postgersql/testDB:/docker-entrypoint-initdb.d